module ClubviRu.Debug.URITest where
import ClubviRu.URIParser
import SiteGen.LinkExtractor
import System.IO
import Text.Peggy
  
{- readFile "c:/Users/Victor/Documents/wrk/newsite/anotherAttemptDestination/index.htm"  -}

links = ["http://www.google.com/jsapi","/static/js/googleanalytics.js","http://www.google.com/cse/t13n?form=cse-search-box&t13n_langs=ru","http://www.google.com/cse/brand?form=cse-search-box&lang=ru","/static/js/jquery-1.4.2.min.js","/static/js/googleanalytics.js","/static/css/indexstyle.css","/","/static/img/vimain3.png","/hymn.php","/zapovedi.php","/history/mainhistory.shtml","/whatisclub/clubmain.html","/kontakt/kontakts.htm","/kafedry/angl/","/kafedry/angl2/","/kafedry/inyaz/","/kafedry/sredn/","/kafedry/zvi/","/kafedry/rom/","/kafedry/bw/1.pdf","/kafedry/dv/","/institut-legenda/","/movies/65let/","/people.htm","/newVIIA.htm","/songs.htm","/bayki.htm","/mayor.php","/RekrytingClub/kadr_main.php","/rusdelo.htm","/health.htm","http://major-viiakov.livejournal.com/","/kp.htm","/tp.htm","/redp.php","/canadohodets.htm","http://novorus.info/","http://rusvesna.su/","http://glagol.in.ua/","http://anna-news.info/","http://arabistika2004.narod.ru","http://arabistika.101.ru/","http://www.zapad-83.com/","http://www.russia-asean.com/","http://www.clubviiy.spb.ru/","http://www.ukrclubvi.com.ua/","http://www.un-museum.ru/","http://veteranangola.ru/","http://redstar.ru/","http://mdiplomat.ru/","http://www.namakon.ru/","http://www.igorgolovko.ucoz.ru/","http://www.mibas.ru/ru/general_info/ispoldir","http://www.zavtra.ru/","http://advertos.narod.ru/","http://www.hubara-rus.ru/","/orlov.htm","http://www.elitaflora.ru/","http://www.fondnagrada.com/content/blogcategory/10/9/","http://www.mse-msu.ru/","http://www.femida-consult.ru/","http://www.srduma.ru/35_1758.html","http://www.ivanlukashov.ru/","http://www.nathalievico.ru/","http://www.smi-antiterror.ru/osj/blogs/blog.htm?id=5@cmsVBVideoBlog","http://www.vladimir-pautov.ru/","http://www.proza.ru/avtor/chura","http://www.art-flora.ru/","http://www.tpp-inform.ru/","http://gb.1tv.com.ua/ru/news/2011/01/24/3","http://www.ad-astro.com/","http://www.ctp.ru/","http://www.e-ling.ru/","http://www.nuclear.ru/","http://www.atomic-energy.ru/smi/2011/04/30/21805","http://divapro.biz/","http://yazyk.net/index.php?option=com_content&task=view&id=70&Itemid=1","http://zhurnal.lib.ru/b/blockij_o_m/","http://vkimo.com/","http://proza.ru/author/saliakhov/","http://www.anspa.ru/","http://www.vesti.ru/news/","http://www.weltsprachen.at/","http://www.verussa.at/","http://www.lowtech-m.com/","http://www.pravo2y.ru/astahov/","http://www.vostok-93.ru/","http://minenko.carconsulting.ru","http://www.vostok.7575.ru/","http://www.zobin.ru/","http://www.vumo.ru","http://znat.ru/","http://www.peremeny.ru/books/osminog/category/nebopolitica","http://www.shiningworld.ru/","http://www.mid.cexpo.ru/site.xp/052055056.html","http://www.glowers.net/mainsite/","http://www.nebopolitica.ru/","http://netocracy.us/","/pishut.htm","/static/js/menu.js","/static/img/clip/znamays.png","/news/bushuev//1.jpg","/news/bushuev//1s.jpg","/news/bushuev//","http://noviyvek.org/ru/diamondcross.html","/static/img/br/diamondcross.jpg","http://www.clubvi.ru"]

links1 = [Right (ParseResult {host = "www.google.com", path = "/jsapi"})
         ,Right (ParseResult {host = "", path = "/static/js/googleanalytics.js"})
         ,Right (ParseResult {host = "www.google.com", path = "/cse/t13n"})
         ,Right (ParseResult {host = "www.google.com", path = "/cse/brand"})
         ,Right (ParseResult {host = "", path = "/static/js/jquery-1.4.2.min.js"})
         ,Right (ParseResult {host = "", path = "/static/js/googleanalytics.js"})
         ,Right (ParseResult {host = "", path = "/static/css/indexstyle.css"})
         ,Right (ParseResult {host = "", path = "/"})
         ,Right (ParseResult {host = "", path = "/static/img/vimain3.png"})
         ,Right (ParseResult {host = "", path = "/hymn.php"})
         ,Right (ParseResult {host = "", path = "/zapovedi.php"})
         ,Right (ParseResult {host = "", path = "/history/mainhistory.shtml"})
         ,Right (ParseResult {host = "", path = "/whatisclub/clubmain.html"})
         ,Right (ParseResult {host = "", path = "/kontakt/kontakts.htm"})
         ,Right (ParseResult {host = "", path = "/kafedry/angl/"})
         ,Right (ParseResult {host = "", path = "/kafedry/angl2/"})
         ,Right (ParseResult {host = "", path = "/kafedry/inyaz/"})
         ,Right (ParseResult {host = "", path = "/kafedry/sredn/"})
         ,Right (ParseResult {host = "", path = "/kafedry/zvi/"})
         ,Right (ParseResult {host = "", path = "/kafedry/rom/"})
         ,Right (ParseResult {host = "", path = "/kafedry/bw/1.pdf"})
         ,Right (ParseResult {host = "", path = "/kafedry/dv/"})
         ,Right (ParseResult {host = "", path = "/institut-legenda/"})
         ,Right (ParseResult {host = "", path = "/movies/65let/"})
         ,Right (ParseResult {host = "", path = "/people.htm"})
         ,Right (ParseResult {host = "", path = "/newVIIA.htm"})
         ,Right (ParseResult {host = "", path = "/songs.htm"})
         ,Right (ParseResult {host = "", path = "/bayki.htm"})
         ,Right (ParseResult {host = "", path = "/mayor.php"})
         ,Right (ParseResult {host = "", path = "/RekrytingClub/kadr_main.php"})
         ,Right (ParseResult {host = "", path = "/rusdelo.htm"})
         ,Right (ParseResult {host = "", path = "/health.htm"})
         ,Right (ParseResult {host = "major-viiakov.livejournal.com", path = "/"})
         ,Right (ParseResult {host = "", path = "/kp.htm"})
         ,Right (ParseResult {host = "", path = "/tp.htm"})
         ,Right (ParseResult {host = "", path = "/redp.php"})
         ,Right (ParseResult {host = "", path = "/canadohodets.htm"})
         ,Right (ParseResult {host = "novorus.info", path = "/"})
         ,Right (ParseResult {host = "rusvesna.su", path = "/"})
         ,Right (ParseResult {host = "glagol.in.ua", path = "/"})
         ,Right (ParseResult {host = "anna-news.info", path = "/"})
         ,Right (ParseResult {host = "", path = "http://arabistika2004.narod.ru"})
         ,Right (ParseResult {host = "arabistika.101.ru", path = "/"})
         ,Right (ParseResult {host = "www.zapad-83.com", path = "/"})
         ,Right (ParseResult {host = "www.russia-asean.com", path = "/"})
         ,Right (ParseResult {host = "www.clubviiy.spb.ru", path = "/"})
         ,Right (ParseResult {host = "www.ukrclubvi.com.ua", path = "/"})
         ,Right (ParseResult {host = "www.un-museum.ru", path = "/"})
         ,Right (ParseResult {host = "veteranangola.ru", path = "/"})
         ,Right (ParseResult {host = "redstar.ru", path = "/"})
         ,Right (ParseResult {host = "mdiplomat.ru", path = "/"})
         ,Right (ParseResult {host = "www.namakon.ru", path = "/"})
         ,Right (ParseResult {host = "www.igorgolovko.ucoz.ru", path = "/"})
         ,Right (ParseResult {host = "www.mibas.ru", path = "/ru/general_info/ispoldir"})
         ,Right (ParseResult {host = "www.zavtra.ru", path = "/"})
         ,Right (ParseResult {host = "advertos.narod.ru", path = "/"})
         ,Right (ParseResult {host = "www.hubara-rus.ru", path = "/"})
         ,Right (ParseResult {host = "", path = "/orlov.htm"})
         ,Right (ParseResult {host = "www.elitaflora.ru", path = "/"})
         ,Right (ParseResult {host = "www.fondnagrada.com", path = "/content/blogcategory/10/9/"})
         ,Right (ParseResult {host = "www.mse-msu.ru", path = "/"})
         ,Right (ParseResult {host = "www.femida-consult.ru", path = "/"})
         ,Right (ParseResult {host = "www.srduma.ru", path = "/35_1758.html"})
         ,Right (ParseResult {host = "www.ivanlukashov.ru", path = "/"})
         ,Right (ParseResult {host = "www.nathalievico.ru", path = "/"})
         ,Right (ParseResult {host = "", path = "http://www.smi-antiterror.ru/osj/blogs/blog.htm"})
         ,Right (ParseResult {host = "www.vladimir-pautov.ru", path = "/"})
         ,Right (ParseResult {host = "www.proza.ru", path = "/avtor/chura"})
         ,Right (ParseResult {host = "www.art-flora.ru", path = "/"})
         ,Right (ParseResult {host = "www.tpp-inform.ru", path = "/"})
  ,Right (ParseResult {host = "gb.1tv.com.ua", path = "/ru/news/2011/01/24/3"})
  ,Right (ParseResult {host = "www.ad-astro.com", path = "/"})
,Right (ParseResult {host = "www.ctp.ru", path = "/"})
,Right (ParseResult {host = "www.e-ling.ru", path = "/"})
,Right (ParseResult {host = "www.nuclear.ru", path = "/"})
,Right (ParseResult {host = "www.atomic-energy.ru", path = "/smi/2011/04/30/21805"})
,Right (ParseResult {host = "divapro.biz", path = "/"})
,Right (ParseResult {host = "yazyk.net", path = "/index.php"})
,Right (ParseResult {host = "zhurnal.lib.ru", path = "/b/blockij_o_m/"})
,Right (ParseResult {host = "vkimo.com", path = "/"})
,Right (ParseResult {host = "proza.ru", path = "/author/saliakhov/"})
,Right (ParseResult {host = "www.anspa.ru", path = "/"})
,Right (ParseResult {host = "www.vesti.ru", path = "/news/"})
,Right (ParseResult {host = "www.weltsprachen.at", path = "/"})
,Right (ParseResult {host = "www.verussa.at", path = "/"})
,Right (ParseResult {host = "www.lowtech-m.com", path = "/"})
,Right (ParseResult {host = "www.pravo2y.ru", path = "/astahov/"})
,Right (ParseResult {host = "www.vostok-93.ru", path = "/"})
,Right (ParseResult {host = "", path = "http://minenko.carconsulting.ru"})
,Right (ParseResult {host = "www.vostok.7575.ru", path = "/"})
,Right (ParseResult {host = "www.zobin.ru", path = "/"})
,Right (ParseResult {host = "", path = "http://www.vumo.ru"})
,Right (ParseResult {host = "znat.ru", path = "/"})
,Right (ParseResult {host = "www.peremeny.ru", path = "/books/osminog/category/nebopolitica"})
,Right (ParseResult {host = "www.shiningworld.ru", path = "/"})
,Right (ParseResult {host = "www.mid.cexpo.ru", path = "/site.xp/052055056.html"})
,Right (ParseResult {host = "www.glowers.net", path = "/mainsite/"})
,Right (ParseResult {host = "www.nebopolitica.ru", path = "/"})
,Right (ParseResult {host = "netocracy.us", path = "/"})
,Right (ParseResult {host = "", path = "/pishut.htm"})
,Right (ParseResult {host = "", path = "/static/js/menu.js"})
,Right (ParseResult {host = "", path = "/static/img/clip/znamays.png"})
,Right (ParseResult {host = "", path = "/news/bushuev//1.jpg"})
,Right (ParseResult {host = "", path = "/news/bushuev//1s.jpg"})
,Right (ParseResult {host = "", path = "/news/bushuev//"})
,Right (ParseResult {host = "noviyvek.org", path = "/ru/diamondcross.html"})
,Right (ParseResult {host = "", path = "/static/img/br/diamondcross.jpg"})
,Right (ParseResult {host = "", path = "http://www.clubvi.ru"})]

parseT str = parseString uRIP str str  
